services:
  nginx:
    build: ./nginx
    ports:
      - 443:443
    networks:
      - orchestra
    restart: always

  wordpress:
    build: ./wordpress
    networks:
      - orchestra
    restart: always

  mariadb:
    build: ./mariadb
    networks:
      - orchestra
    restart: always

# volumes:
#   db:
#
#   website:

networks:
  orchestra:
    name: "orchestra"


