services:
  nginx:
    build: ./nginx
    ports:
      - 443:443
    # networks:
      # - orchestra

  # wordpress:
    # build:
      # dockerfile: "./wordpress/dockerfile"
    # networks:
      # - orchestra

  # mariadb:
    # build:
      # dockerfile: "./mariadb/dockerfile"
    # networks:
      # - orchestra

# volumes:
  # db:

  # website:

# networks:
  # orchestra:
    # driver: default
    # name: "orchestra"


