services:
  nginx:
    build: ./nginx
    ports:
      - 443:443
    networks:
      - orchestra
    restart: always
    volumes:
      - website:/www

  wordpress:
    build: ./wordpress
    networks:
      - orchestra
    restart: always

  mariadb:
    build: ./mariadb
    networks:
      - orchestra
    restart: always
    volumes:
      - db:/var/lib/mysql

volumes:
  website:
    driver: local
    driver_opts:
      type: none
      device: /home/mde-beer/data/website
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/mde-beer/data/db
      o: bind

networks:
  orchestra:
    name: "orchestra"
