services:
  nginx:
    build: nginx/
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
  wordpress:
    build: wordpress/
    container_name: wp-php
    volumes:
      - ./web:/var/www/html
  mariadb:
    build: mariadb/
    container_name: mariadb
